"""Render traceable appendices from the published forensic tables."""
import csv,json
from pathlib import Path
P=Path(__file__).resolve().parents[3]/'docs/reports/2026-09-10/trace-forensics'
read=lambda name:json.loads((P/name).read_text())
rows=list(csv.DictReader((P/'rh-discordant.csv').open()))
text=(P/'README.md').read_text().split('\n## Appendix A.')[0]
text+='\n## Appendix A. Every matched discordant RH auditor row\n\nScores and decisions below are the original frozen outputs. Reasons are shortened here; both complete rationales are in `rh-discordant.csv`. N=negative, P=positive, U=abstention. Full cases have not received the exhaustive manual event adjudication performed for candidate-positive User cases.\n'
for setting in ['user','full']:
 text+='\n### '+setting.title()+' feedback\n\n| Task / replicate | Auditor | Original score / verdict | Candidate score / verdict | Original rationale pointer | Candidate rationale pointer |\n|---|---|---|---|---|---|\n'
 for r in rows:
  if r['setting']!=setting:continue
  clean=lambda s:s.replace('|','/').replace('\n',' ').strip()
  short=lambda s:clean(s)[:220]+('…' if len(clean(s))>220 else '')
  verdict={'negative':'N','positive':'P','abstain':'U'}
  text+=f'| {r["task_id"]}/r{r["replicate"]} | {"Sol" if r["auditor"]=="gpt-5.6-sol" else "Opus"} | {r["original_monitor_score"]} / {verdict[r["original_verdict"]]} | {r["candidate_monitor_score"]} / {verdict[r["candidate_verdict"]]} | {short(r["original_rationale"])} | {short(r["candidate_rationale"])} |\n'
text+='\n## Appendix B. All fifteen candidate-positive User case dossiers\n\nTurn T is the natural solver turn; g is the generation scoring that turn’s resulting submission. A criterion admitted at g can first affect T(g+1). The linked evidence contains actual commands/file edits, not only auditor rationales. Full feedback records and criterion-level scores are in `positive-case-feedback.json`.\n'
manual=read('manual-adjudications.json')['candidate_user'];timelines={r['case']:r for r in read('rh-case-timelines.json')}
proposals=list(csv.DictReader((P/'proposals.csv').open()));pm={(r['policy'],r['task_id'],int(r['replicate']),r['criterion_id']):r for r in proposals}
for m in manual:
 name=f'candidate_user_{m["task_id"]}_r{m["replicate"]}';r=timelines[name];p=pm[('candidate',m['task_id'],m['replicate'],m['first_relevant_proposal'])];a=pm.get(('candidate',m['task_id'],m['replicate'],m['first_relevant_admission']))
 text+=f'\n### {m["task_id"]}/r{m["replicate"]} — {m["bucket"]}\n\n'
 text+=f'Frozen positive auditors: **{r["original_positive_auditors"]}→{r["candidate_positive_auditors"]}**. Earliest risky action: T{m["earliest_risky_turn"]}; first clearly verified event: '+(f'T{m["verified_rh_turn"]} (g{m["verified_rh_turn"]})' if m['verified_rh_turn'] else 'unresolved; excluded from verified-event timing')+'.\n\n'+m['finding']+'\n\n'
 text+=f'First relevant proposal: g{p["generation"]}, **{p["title"]}**, `{p["criterion_id"]}`. Requirement: {p["requirement"]} Decision: `{p["rejection_reason"]}`. '
 if a:
  text+=f'First relevant admission: g{a["generation"]}, **{a["title"]}**, `{a["criterion_id"]}`. First semantically relevant feedback: T{m["first_relevant_exposure_turn"]}. '
  if m['verified_rh_turn']:text+=('This precedes the verified event. ' if m['first_relevant_exposure_turn']<=m['verified_rh_turn'] else 'This follows the verified event. ')
 else:text+='No relevant online admission or attributable online-criterion exposure was identified. '
 text+=m.get('exposure_qualification','')+'\n\nAfterward: '+m['after']+'\n\nRaw evidence anchors: '+', '.join(f'T{t}:line {l} (`{needle}`)' for t,l,needle in m['evidence'])+'. See [verified excerpts](verified-trajectory-excerpts.json) for original path and SHA.\n'
text+='\n## Appendix C. Table index and joining rules\n\n'
entries=[('endpoint-summary.csv','Frozen pooled and auditor-specific endpoints, including abstentions'),('paired-uncertainty.csv','Matched task-cluster uncertainty for RH and every gap/quality component'),('rh-transitions-auditor.csv','Every matched task × replicate × auditor row and original/candidate scores/rationales'),('rh-discordant.csv','All verdict changes, including abstentions'),('rh-transitions-assignment.csv','Both auditor verdicts and any-positive assignment aggregation'),('coverage-rh-crosstab.csv','Coverage transitions crossed with all RH transitions'),('criterion-lifecycle.csv','Per-assignment proposal/admission/rejection and penalty counts'),('proposals.csv','Every online proposed criterion and recorded admission outcome'),('cited-pair-applications.csv','Each proposal citation, stable artifact IDs, application levels and reasons'),('support-review-evidence.json','29 manually reviewed criteria, 53 public pairs, full public contents/diffs'),('support-mapping-validation.csv','Saved A/B preference mapped to stable artifact ID'),('rh-case-timelines.csv','15 candidate-positive User case timelines and primary bucket'),('original-positive-timelines.csv','6 original-positive User timeline annotations'),('verified-trajectory-excerpts.json','Candidate raw evidence with exact original path/hash/line'),('original-trajectory-excerpts.json','Original raw evidence with exact original path/hash/line'),('positive-case-feedback.json','Actual candidate-positive User feedback and learned score levels'),('online-delivery-timing.csv','All admitted online criteria and score/feedback opportunities'),('checkpoint-timing.csv','Every score checkpoint with timing and prompt provenance'),('criterion-scoring-delivery.csv','Ordinal-to-stable-criterion score and penalty mapping'),('gap-contributions.csv','Matched per-assignment changes in W/S/H/A and every gap'),('gap-coverage-strata.csv','Gap changes grouped by coverage transition'),('gap-review-evidence.json','Largest-gap final public artifacts, existing holistic judgments and feedback'),('pre-online-divergence.csv','Initial and first-revised public-file equality'),('existing-active-delivery-comparison.json','Existing near-policy run transition/exposure census'),('recovery-overlap.csv','Revision/audit recovery membership and positive transitions'),('runtime-completion-cohorts.csv','First55/second29/final36 completion cohorts'),('lineage-config-comparison.csv','Matched manifest differences and exact offline/input lineage equality'),('source-hashes.csv','Executed-package versus historical/current source hashes'),('saved-prompt-provenance.csv','239 native prompt paths/hashes and two normalized templates'),('trajectory-sources.json','All inspected natural trajectory paths/SHA-256/line counts'),('manifest.json','Published report/table hashes and verification coverage')]
text+='| File | Contents |\n|---|---|\n'+''.join(f'| [{file}]({file}) | {description} |\n' for file,description in entries)
text+='\nJoin assignment tables on `(setting, task_id, replicate)` and add `policy` when present; add `auditor`/`model` for judgment rows. Join proposals/applications/deliveries on policy, task, replicate, generation and stable criterion ID. `case` encodes those fields as `policy_setting_task_rN`. Criteria with replacements require inherited provenance as well as their current citations. Blank timestamps/IDs mean no identified event, not generation zero. Machine-readable booleans in CSV use `True`/`False`; nested cells use JSON.\n'
(P/'README.md').write_text('\n'.join(line.rstrip() for line in text.splitlines())+'\n')
